name = "edge-limiter"
main = "src/index.ts"
compatibility_date = "2026-04-28"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "6264fac76d8148638b973f56b5bc7b0d"

[[d1_databases]]
binding = "DB"
database_name = "edge-limiter-db"
database_id = "f5939813-c18d-4cb3-94a7-df5f3ac39b78"

[[queues.producers]]
binding = "LOG_QUEUE"
queue = "rate-limit-logs"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiter"]

[[queues.consumers]]
queue = "rate-limit-logs"
max_batch_size = 10
max_batch_timeout = 5

[triggers]
crons = ["0 0 * * *"]

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "edge_limiter_analytics"